export const requiredText = 'Este campo es requerido'
export const emailerrorText = 'Debe ser un e-mail válido'
export const phonelenghtText = 'El teléfono debe tener 10 caracteres'
export const phoneformatText = 'Solo debe contener números'
export const ziplenghtText = 'El código postal debe tener 5 caracteres'
